# text
foreground           #313135
# base
background           #F7FEFF
# subtext0
title_fg             #C3C3D4
color8  #575965
color0  #313135
color9  #DE2F2F
color1  #B62A2A
color10 #55D324
color2  #12B55B
color11 #DEBE2F
color3  #D39810
color12 #1551F6
color4  #0A3BC0
color13 #771CF7
color5  #5F0AC0
color14 #1DE8F2
color6  #15BAF6
color15 #F7FEFF
color7  #C3C3D4
